version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      common-workflows:
        patterns:
          - "trento-project/.github*"
    cooldown:
      default-days: 14
      exclude:
        - "trento-project/.github*"
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@eslint*"
  - package-ecosystem: "npm"
    directory: "/test/e2e"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
    groups:
      cypress:
        patterns:
          - "cypress*"
          - "@cypress*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint*"
