version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "daily"
    groups:
      npm-production:
        dependency-type: "production"
      npm-development:
        dependency-type: "development"
  - package-ecosystem: "npm"
    directory: "/test/e2e"
    schedule:
      interval: "weekly"
    groups:
      npm-e2e:
        patterns:
          - "*"
