name-template: $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION
categories:
  - title: Features
    labels:
      - feature
      - enhancement
  - title: Bug Fixes
    labels:
      - fix
      - bugfix
      - bug
  - title: Maintenance
    labels:
      - chore
      - ci
      - tech-debt
  - title: Dependencies
    label: dependencies
    collapse-after: 3
version-resolver:
  major:
    labels:
      - major
      - breaking
  minor:
    labels:
      - feature
      - minor
  patch:
    labels:
      - patch
      - bug
  default: patch
exclude-labels:
  - skip-release-notes
template: |
  $CHANGES
