version: "3"

services:

  postgres:
    volumes:
      - ./container_fixtures/postgres/init_wanda_db.sh:/docker-entrypoint-initdb.d/init_wanda_db.sh:ro

  checks: 
      image: ghcr.io/trento-project/checks:rolling
      volumes: 
        - /usr/share/trento/checks

  wanda:
    image: ghcr.io/trento-project/trento-wanda:demo
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/postgres
      SECRET_KEY_BASE: s2ZdE+3+ke1USHEJ5O45KT364KiXPYaB9cJPdH3p60t8yT0nkLexLBNw8TFSzC7k
      AMQP_URL: amqp://trento:trento@rabbitmq:5672
      ACCESS_TOKEN_ENC_SECRET: s2ZdE+3+ke1USHEJ5O45KT364KiXPYaB9cJPdH3p60t8yT0nkLexLBNw8TFSzC7k
      CORS_ORIGIN: "http://localhost:4000"
    depends_on:
      - postgres
      - rabbitmq
      - checks
    ports:
      - 4001:4000
    entrypoint: /bin/sh -c "/app/bin/wanda eval 'Wanda.Release.init()' && /app/bin/wanda start"
    volumes_from: [checks]