# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

---
name: Backport PR

on:
  pull_request:
    branches: [main]
    types: [closed, labeled]

jobs:
  backport:
    name: Backport
    uses: trento-project/.github/.github/workflows/backport-pr.yaml@94dac57211d792dda649383e7f23326b24a9087b # v1.11.0
    secrets:
      gh_token: ${{ secrets.TRENTOBOT_GH_PAT }}
      ssh_key: ${{ secrets.TRENTOBOT_SSH_KEY }}
      gpg_key: ${{ secrets.TRENTOBOT_GPG_KEY }}
