# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

---
name: Backport PR

on:
  pull_request:
    branches: [main]
    types: [closed, labeled]

jobs:
  backport:
    name: Backport
    uses: trento-project/.github/.github/workflows/backport-pr.yaml@d8679bc6bc759e119793a2d59285098613f52055 # v1.10.0
    secrets:
      gh_token: ${{ secrets.TRENTOBOT_GH_PAT }}
      ssh_key: ${{ secrets.TRENTOBOT_SSH_KEY }}
      gpg_key: ${{ secrets.TRENTOBOT_GPG_KEY }}
