name: Release

on:
  push:
    branches:
      - main
      - release
    paths:
      - "VERSION"

concurrency: ${{ github.workflow }}

jobs:
  release:
    name: Git Release
    uses: trento-project/.github/.github/workflows/git-release.yaml@0902a0796c4c6a9b46ae9e84b244733a924a48e5 # v1.4.1
    with:
      triggering_branch: ${{ github.ref_name }}
    secrets:
      gh_token: ${{ secrets.TRENTOBOT_GH_PAT }}
      ssh_key: ${{ secrets.TRENTOBOT_SSH_KEY }}
      gpg_key: ${{ secrets.TRENTOBOT_GPG_KEY }}

  publish-containers:
    name: Publish GHCR Containers
    uses: trento-project/.github/.github/workflows/publish-containers.yaml@8eb0cca8f3ddfa9927356bb38dde2de86c91219b # v1.4.0
    needs:
      - release
    strategy:
      matrix:
        include:
          - mix_env: prod
            tag: ${{ needs.release.outputs.version }}
          - mix_env: prod
            tag: rolling
          - mix_env: demo
            tag: demo
    with:
      image_name: trento-web
      tag: ${{ matrix.tag }}
      extra_build_args: |
        MIX_ENV=${{ matrix.mix_env }}
        GTM_ID=${{ vars.GTM_ID }}
    secrets:
      gh_token: ${{ secrets.TRENTOBOT_GH_PAT }}
      ssh_key: ${{ secrets.TRENTOBOT_SSH_KEY }}

  obs-sync:
    name: Update OBS package (${{ matrix.name }})
    needs:
      - release
    if: fromJSON(vars.OBS_ENABLED)
    strategy:
      matrix:
        include:
          - obs_project: ${{ vars.OBS_PROJECT_STABLE }}
            name: stable
          - obs_project: ${{ vars.OBS_PROJECT_ROLLING }}
            name: rolling
    uses: trento-project/.github/.github/workflows/obs-sync.yaml@8eb0cca8f3ddfa9927356bb38dde2de86c91219b # v1.4.0
    with:
      update_changelog: true
      obs_project: ${{ matrix.obs_project }}
      obs_package: ${{ vars.OBS_PACKAGE }}
    secrets:
      gh_token: ${{ secrets.TRENTOBOT_GH_PAT }}
      obs_user: ${{ secrets.OBS_USER }}
      obs_pass: ${{ secrets.OBS_PASS }}
      obs_ssh_key: ${{ secrets.OBS_SSH_KEY }}
