# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

name: Rerun failed jobs

on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
        type: string

jobs:
  rerun:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:
      - name: Rerun failed jobs
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh run watch ${{ inputs.run_id }} > /dev/null 2>&1
          gh run rerun ${{ inputs.run_id }} --failed
